# Generated by Django 3.2 on 2021-04-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='application',
            name='program',
        ),
    ]
