# Generated by Django 3.2 on 2021-04-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('PE', 'Pending'), ('RE', 'Rejected'), ('DE', 'Deferred')], default='PE', max_length=2)),
            ],
        ),
    ]
