# Generated by Django 3.2 on 2021-04-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20210424_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='grade',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='university.program'),
        ),
    ]
